definitions:
  model.Item:
    properties:
      create_at:
        type: integer
      device_id:
        type: string
      expires_at:
        type: integer
      id:
        type: string
      is_oauth:
        type: boolean
      last_activity_at:
        type: integer
      props:
        additionalProperties:
          type: string
        type: object
      roles:
        type: string
      token:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      description: Essa rota é privada com o token valido (Bearer)
      parameters:
      - description: add Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/model.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - health
  /v1/health/check:
    get:
      consumes:
      - application/json
      parameters:
      - description: add Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/model.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - health
  /v1/item:
    get:
      consumes:
      - application/json
      description: Essa rota é privada com o token valido (Bearer)
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Exembro de Buscar item por id
      tags:
      - item
    post:
      consumes:
      - application/json
      description: Essa rota é privada com o token valido (Bearer)
      parameters:
      - description: add Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/model.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Item'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Exembro de como postar algum item
      tags:
      - item
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
